.readthedocs.yaml
- [x ] Have you followed the guidelines for contributing?
- [ x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ x] Have you successfully run `tox`?
-----
Fixes the RTD build.
=> Fix path in readthedocs yaml

docs/.custom_wordlist.txt, docs/index.rst, docs/tutorials/index.rst
- Navig. grid fix
- Added info to HP
- Spellcheck fix
=> Improve the docs homepage

.github/workflows/policy.yaml, .github/workflows/qa.yaml
=> fix(ci): use main branch from starflow

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/task.yaml
=> feat: add issue templates

imagecraft/cli.py, pyproject.toml, snap/snapcraft.yaml
=> feat: add bash completion script

snap/snapcraft.yaml
---
Use uv to build the imagecraft part in the snap.
Fixes #83
CRAFT-4062
=> feat: Build snap with uv

pyproject.toml, uv.lock
=> build(deps): refresh uv.lock

imagecraft/errors.py, imagecraft/pack/__init__.py, imagecraft/pack/chroot.py, imagecraft/pack/diskutil.py, imagecraft/pack/grubutil.py, imagecraft/pack/image.py, imagecraft/services/pack.py, tests/integration/test_application.py, tests/spread/pack/grub/imagecraft.yaml, tests/spread/pack/grub/task.yaml, tests/spread/pack/overlay/task.yaml, tests/unit/services/test_pack.py
---
Implement grub installation in the image after the disk is created.  
The chroot handling is forked from craft-parts.
=> Implement grub installation in the image

pyproject.toml, uv.lock
=> build(deps): update craft-cli and craft-application versions

.github/workflows/cla-check.yaml
---
Remove `cla-check.yaml` workflow as it was replaced by `policy.yaml` workflow from starbase.
=> ci: remove superseded CLA check

imagecraft/pack/diskutil.py, imagecraft/pack/grubutil.py, imagecraft/subprocesses.py, snap/snapcraft.yaml, spread.yaml, tests/spread/commons/init/task.yaml, tests/spread/pack/complex/imagecraft.yaml, tests/spread/pack/complex/task.yaml, tests/spread/pack/grub/task.yaml, tests/spread/pack/overlay/task.yaml, tests/spread/pack/simple/task.yaml
=> Fix spread tests

docs/how-to-guides/basic_image.rst
=> docs: add instructions to pack in a multipass VM in the basic how-to

imagecraft/errors.py, imagecraft/pack/chroot.py, imagecraft/pack/grubutil.py, tests/unit/pack/test_chroot.py
---
When trying to install GRUB, if `/boot/efi` mountpoint is missing the installation must be skipped (because it means the conditions to install GRUB are not met) but the packing must not fail.
=> Fix grub install

imagecraft/pack/grubutil.py, imagecraft/pack/image.py, tests/unit/pack/test_gptutil.py, tests/unit/pack/test_image.py
=> feat: context manager for image loop dev management

tests/unit/pack/test_grubutil.py
---
Add tests for `setup_grub()`.
=> Test grub util

imagecraft/application.py, imagecraft/cli.py, imagecraft/pack/diskutil.py, imagecraft/pack/gptutil.py, imagecraft/pack/grubutil.py, imagecraft/services/pack.py, tests/spread/pack/grub/task.yaml, tests/unit/pack/test_diskutil.py, tests/unit/pack/test_grubutil.py
---
Improve and harmonize logs and displayed messages at various verbosity levels.
=> Clean output

Makefile, imagecraft/models/project.py, tests/unit/models/test_project.py, uv.lock
---
- Specifically update craft-application to 5.1.0 and fix build-on/build-for usage.
- Add missing system deps setup for tests.
=> build(deps): update deps

.github/.jira_sync_config.yaml
---
Use the `IMAGECRAFT` project to sync issues on JIRA
=> ci: update JIRA sync project key

imagecraft/grammar.py, imagecraft/models/project.py, imagecraft/services/lifecycle.py, imagecraft/services/project.py, imagecraft/templates/simple/imagecraft.yaml.j2, pyproject.toml, tests/conftest.py, tests/integration/test_application.py, tests/spread/pack/complex/imagecraft.yaml, tests/spread/pack/grub/imagecraft.yaml, tests/spread/pack/overlay/imagecraft.yaml, tests/spread/pack/simple/imagecraft.yaml, tests/unit/models/test_project.py, tests/unit/services/test_lifecycle.py, tests/unit/test_application.py, tests/unit/test_grammar.py, uv.lock
---
Implement the `filesystems` model as specified in https://docs.google.com/document/d/1MtDUlGkq2txvylU2Gzym3R8zgVALAWD9w6GSGix4fYs/edit?tab=t.0
The actual work of using these filesystems definitions to properly distribute the content to partitions will be done by craft-parts in a near future. Wait to update the how-to in the docs until this is done.
IMAGECRAFT-24
=> Add filesystems model

docs/how-to-guides/basic_image.rst
---
Just adding a missing step regarding fresh Ubuntu 24.04 install.
=> docs: add missing package install step for QEMU

uv.lock
---
Bumped with `uv sync --upgrade-package urllib3`
=> build(autogen): bump urllib3

.github/workflows/snap.yaml
=> ci(snap): publish snap for PRs and feature branches

docs/reference/imagecraft-yaml-file.rst
---
* Reorder part keys
* Add manual description to `organize`
=> docs: update 'imagecraft.yaml'

docs/about-this-documentation.rst, docs/index.rst
=> docs: add 'About this documentation'

imagecraft/models/__init__.py, imagecraft/models/project.py, imagecraft/services/lifecycle.py, imagecraft/services/project.py, pyproject.toml, snap/snapcraft.yaml, tests/conftest.py, tests/integration/services/test_lifecycle.py, tests/integration/test_application.py, tests/spread/pack/complex/imagecraft.yaml, tests/unit/models/test_project.py, tests/unit/services/test_lifecycle.py, tests/unit/test_application.py, tests/unit/test_grammar.py, uv.lock
---
Support the craft-parts feature to alias the default partition. 
Also adding needed libraries to the snap following https://github.com/canonical/craft-parts/pull/1172
IMAGECRAFT-37
=> Support partition alias 

docs/conf.py, pyproject.toml, tests/spread/pack/grub/imagecraft.yaml, uv.lock
=> fix: whiteout files migration

README.md
---
- remove broken ones
- add badge for codecov, ruff and to get the snap
=> docs: rework badges

imagecraft/application.py, imagecraft/grammar.py, imagecraft/services/project.py, pyproject.toml, spread.yaml, tests/spread/pack/grammar/imagecraft.yaml, tests/spread/pack/grammar/task.yaml, tests/unit/services/test_lifecycle.py, tests/unit/test_grammar.py, uv.lock
---
Adds support for the 'for' statement in advanced grammar.
I did a bit of prep-work and refactoring, so I recommend reviewing per-commit.
Fixes #201 
(IMAGECRAFT-45)
=> feat: support 'for' statements
